backend:
  name: git-gateway


media_folder: static/assets
public_folder: assets

logo_url: /assets/ocw-logo-black.svg


collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: outbound
    label: Outbound
    folder: content/outbound
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
# default: "/uploads/chocolate-dogecoin.jpg",
# media_library:
#   config:
#     multiple: true
